name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build and Export
        run: |
          npm run build
          cp -r public/* out/

      - name: Configure custom domain
        run: |
          touch ./out/.nojekyll
          cp public/CNAME ./out/

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          branch: gh-pages
          folder: out
          clean: true
          token: ${{ secrets.GITHUB_TOKEN }}
          git-config-name: GitHub Actions
          git-config-email: github-actions@github.com